
TrajectoryPlannerROS:
  acc_lim_th: 1.0
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_rotational_vel: 0.7
  min_in_place_rotational_vel: 0.3
  escape_vel: -0.1
  holonomic_robot: false
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.02
  sim_time: 3
  sim_granularity: 0.02
  vx_samples: 10
  vtheta_samples: 30
  
  meter_scoring: true
  oscillation_reset_dist: 0.5
  prune_plan: true
