costmap_common_params:
  robot_base_frame: "base_link"
  transform_tolerance: 0.5

  # Configurazione dello strato degli ostacoli
  obstacle_layer:
    max_obstacle_height: 2.0
    origin_z: 0.0
    z_resolution: 0.2
    z_voxels: 10
    track_unknown_space: true
    unknown_threshold: 15
    mark_threshold: 10
    obstacle_range: 5
    raytrace_range: 3.0

  # Configurazione dello strato di inflazione
  inflation_layer:
    inflation_radius: 0.55
    cost_scaling_factor: 10.0

