global_costmap:
  global_frame: "map"
  robot_base_frame: "base_link"
  update_frequency: 2.0  # Frequenza di aggiornamento
  publish_frequency: 1.0  # Frequenza di pubblicazione
  resolution: 0.05  # Risoluzione
  rolling_window: true  # Il costmap globale segue il robot
  width: 100  # Larghezza del costmap
  height: 100  # Altezza del costmap

  # Layer di inflazione
  inflation_radius: 0.4
