global_costmap:
  global_frame: "map"
  robot_base_frame: "base_link"
  update_frequency: 1.0  # Frequenza di aggiornamento
  publish_frequency: 5.0  # Frequenza di pubblicazione
  width: 120.0  # Larghezza del costmap globale in metri
  height: 60.0  # Altezza del costmap globale in metri
  resolution: 0.05  # Risoluzione in metri per cella
  origin_x: -60.0  # Origine in x per centrare il costmap
  origin_y: -50.0  # Origine in y per centrare il costmap
  static_map: true  # Usa una mappa statica
  rolling_window: false  # Costmap statico
  inflation_radius: 0.5  # Inflazione per evitare collisioni
  footprint:
    - [0.5, 0.5]
    - [0.5, -0.5]
    - [-0.5, -0.5]
    - [-0.5, 0.5]  # Footprint del robot
  footprint_padding: 0.1  # Padding aggiuntivo per evitare collisioni

