local_costmap:
  global_frame: "odom"
  robot_base_frame: "base_link"
  update_frequency: 10.0
  publish_frequency: 5.0
  width: 30.0
  height: 30.0
  resolution: 0.05
  origin_x: -15.0
  origin_y: -15.0
  static_map: false
  rolling_window: true
  inflation_radius: 0.01
  footprint:
  - [0.5, 0.5]
  - [0.5, -0.5]
  - [-0.5, -0.5]
  - [-0.5, 0.5]

  footprint_padding: 0.01  # Padding aggiuntivo per evitare collisioni

