local_costmap:
  global_frame: "odom"
  robot_base_frame: "base_link"
  update_frequency: 10.0  # Frequenza di aggiornamento
  publish_frequency: 10.0  # Frequenza di pubblicazione
  resolution: 0.05  # Risoluzione
  rolling_window: true  # Il costmap locale segue il robot
  width: 20.0  # Larghezza del costmap
  height: 20.0  # Altezza del costmap

  # Layer di inflazione
  #inflation_radius: 0.5

